# Generated by Django 6.1 on 2026-08-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_cargar_catalogo_necesidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportenecesidad',
            name='fecha_realizacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro'),
        ),
    ]
