# Generated by Django 6.1 on 2026-08-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puntos', '0002_cargar_catalogos'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoafectado',
            name='poblacion_total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Población total'),
        ),
        migrations.AlterField(
            model_name='puntoafectado',
            name='poblacion_vulnerable',
            field=models.CharField(choices=[('NINGUNA', 'Ninguna'), ('ADULTO_MAYOR', 'Adulto mayor'), ('INFANTES', 'Infantes'), ('AMBOS', 'Adulto mayor e infantes')], max_length=20),
        ),
    ]
